import { MenuAdmin } from 'src/app/interfaces/menu-admin';

export const menuItemsSuperAdmin: MenuAdmin[] = [
  // Parent Dashboard
  // Parent Gallery Folder

  {
    id: '1',
    title: 'Dashboard',
    icon: 'dashboard',
    hasSubMenu: false,
    parentId: null,
    routerLink: 'dashboard',
    href: null,
    target: null,
  },
  {
    id: '6',
    title: 'Product',
    icon: 'list_alt',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },

  {
    id: '6sub2',
    title: 'Add Product',
    icon: null,
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'add-product',
    href: null,
    target: null,
  },
  {
    id: '6sub1',
    title: 'Products List',
    icon: null,
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'products',
    href: null,
    target: null,
  },

  {
    id: 'parentThirdParty',
    title: 'Product Settings',
    icon: 'settings_applications',
    hasSubMenu: true,
    parentId: null,
    routerLink: 'brand',
    href: null,
    target: null,
  },
  {
    id: '2',
    title: 'Collections',
    icon: null,
    hasSubMenu: false,
    parentId: 'parentThirdParty',
    routerLink: 'collections',
    href: null,
    target: null,
  },
  {
    id: '2',
    title: 'Vendors',
    icon: null,
    hasSubMenu: false,
    parentId: 'parentThirdParty',
    routerLink: 'vendor',
    href: null,
    target: null,
  },
  {
    id: 'type',
    title: 'Product Type',
    icon: null,
    hasSubMenu: false,
    parentId: 'parentThirdParty',
    routerLink: 'product-type',
    href: null,
    target: null,
  },
  {
    id: 'country',
    title: 'Country',
    icon: null,
    hasSubMenu: false,
    parentId: 'parentThirdParty',
    routerLink: 'country',
    href: null,
    target: null,
  },

  {
    id: 'brand',
    title: 'Brand',
    icon: null,
    hasSubMenu: false,
    parentId: 'parentThirdParty',
    routerLink: 'brand',
    href: null,
    target: null,
  },
  {
    id: 'supplier',
    title: 'Supplier',
    icon: null,
    hasSubMenu: false,
    parentId: 'parentThirdParty',
    routerLink: 'supplier',
    href: null,
    target: null,
  },



  {
    id: '7',
    title: 'Size Chart',
    icon: null,
    hasSubMenu: false,
    parentId: 'parentThirdParty',
    routerLink: 'size-chart',
    href: null,
    target: null,
  },
  {
    id: '8',
    title: 'Stock-Control',
    icon: null,
    hasSubMenu: false,
    parentId: 'parentThirdParty',
    routerLink: 'stock-control',
    href: null,
    target: null,
  },
  {
    id: '110b3',
    title: 'Conversion Rate',
    icon: null,
    hasSubMenu: false,
    parentId: 'parentThirdParty',
    routerLink: 'conversion-rate',
    href: null,
    target: null,
  },
  {
    id: 'I100',
    title: 'Inventory',
    icon: 'inventory',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null
  },
  {
    id: '1212Il',
    title: 'Stock',
    icon: null,
    hasSubMenu: false,
    parentId: 'I100',
    routerLink: 'stock',
    href: null,
    target: null
  },
  {
    id: 'll11I1',
    title: 'Purchase',
    icon: null,
    hasSubMenu: false,
    parentId: 'I100',
    routerLink: 'purchase',
    href: null,
    target: null
  },

  {
    id: '1212ll',
    title: 'Adjustment',
    icon: null,
    hasSubMenu: false,
    parentId: 'I100',
    routerLink: 'adjustment',
    href: null,
    target: null
  },

  {
    id: '9',
    title: 'Orders',
    icon: 'sell',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '3',
    title: 'Customers/Users',
    icon: 'group',
    hasSubMenu: true,
    parentId: null,
    routerLink: 'all-customers',
    href: null,
    target: null,
  },
  {
    id: '3sub1',
    title: 'All Customers',
    icon: null,
    hasSubMenu: false,
    parentId: '3',
    routerLink: 'all-customers',
    href: null,
    target: null,
  },
  {
    id: '3sub2',
    title: 'Tag',
    icon: null,
    hasSubMenu: false,
    parentId: '3',
    routerLink: 'tag',
    href: null,
    target: null,
  },
  // pareny location
  {
    id: 'l100',
    title: 'Locations',
    icon: 'add_location',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null
  },
  {
    id: '1212ll',
    title: 'Zila',
    icon: null,
    hasSubMenu: false,
    parentId: 'l100',
    routerLink: 'zila',
    href: null,
    target: null
  },
  {
    id: 'll1121',
    title: 'City',
    icon: null,
    hasSubMenu: false,
    parentId: 'l100',
    routerLink: 'city',
    href: null,
    target: null
  },

  {
    id: '1212ll',
    title: 'Thana',
    icon: null,
    hasSubMenu: false,
    parentId: 'l100',
    routerLink: 'thana',
    href: null,
    target: null
  },
  {
    id: '11',
    title: 'Issue',
    icon: 'report',
    hasSubMenu: false,
    parentId: null,
    routerLink: 'dashboard-cusrt',
    href: null,
    target: null,
  },
  {
    id: 'p12',
    title: 'Coupon',
    icon: 'dashboard_customize',
    hasSubMenu: false,
    parentId: '12',
    routerLink: 'tag',
    href: null,
    target: null,
  },
  {
    id: 'p12',
    title: 'Bulk Sms/Email',
    icon: 'dashboard_customize',
    hasSubMenu: false,
    parentId: '12',
    routerLink: 'tag',
    href: null,
    target: null,
  },
  {
    id: 'p12',
    title: 'Campaign',
    icon: 'dashboard_customize',
    hasSubMenu: false,
    parentId: '12',
    routerLink: 'tag',
    href: null,
    target: null,
  },
  {
    id: '13',
    title: 'Settings',
    icon: 'settings',
    hasSubMenu: false,
    parentId: null,
    routerLink: 'settings3',
    href: null,
    target: null,
  },
  {
    id: '14',
    title: 'Shipping',
    icon: 'local_shipping',
    hasSubMenu: false,
    parentId: null,
    routerLink: 'shipping-4',
    href: null,
    target: null,
  },
  {
    id: '15',
    title: 'Subscription',
    icon: 'subscriptions',
    hasSubMenu: false,
    parentId: null,
    routerLink: 'subscription-3',
    href: null,
    target: null,
  },

  // Parent Customization
  {
    id: '2',
    title: 'Customization',
    icon: 'tune',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: 'a1',
    title: 'Category Menu',
    icon: null,
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'category-menu',
    href: null,
    target: null,
  },

  {
    id: 'a2',
    title: 'Carousel',
    icon: null,
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'carousel',
    href: null,
    target: null,
  },
  {
    id: 'a3',
    title: 'Shop Info',
    icon: null,
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'shop-info',
    href: null,
    target: null,
  },
  {
    id: 'a4',
    title: 'Footer Data',
    icon: null,
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'footer-data',
    href: null,
    target: null,
  },
  {
    id: 'a5',
    title: 'Promo Advertise',
    icon: null,
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'promo-page',
    href: null,
    target: null,
  },

  {
    id: '4',
    title: 'Category Menu',
    icon: null,
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'category-menu',
    href: null,
    target: null,
  },

  // Parent Products

  {
    id: '9sub1',
    title: 'Regular Order',
    icon: null,
    hasSubMenu: false,
    parentId: '9',
    routerLink: 'regular-orders',
    href: null,
    target: null,
  },
  {
    id: '9sub2',
    title: 'Request Order',
    icon: null,
    hasSubMenu: false,
    parentId: '9',
    routerLink: 'request-order',
    href: null,
    target: null,
  },
  {
    id: '9sub3',
    title: 'Return',
    icon: null,
    hasSubMenu: false,
    parentId: '9',
    routerLink: 'return',
    href: null,
    target: null,
  },
  {
    id: '9sub4',
    title: 'All Invoices',
    icon: null,
    hasSubMenu: false,
    parentId: '9',
    routerLink: 'all-invoice',
    href: null,
    target: null,
  },
  {
    id: '9sub8',
    title: 'Abandoned Cart',
    icon: null,
    hasSubMenu: false,
    parentId: '9',
    routerLink: 'abandoned-cart',
    href: null,
    target: null,
  },
  {
    id: '9sub10',
    title: 'Subscription',
    icon: null,
    hasSubMenu: false,
    parentId: '9',
    routerLink: 'suhna',
    href: null,
    target: null,
  },
  // {
  //   id: '9sub10',
  //   title: 'Subscription',
  //   icon: 'view_list',
  //   hasSubMenu: false,
  //   parentId: '9',
  //   routerLink: 'subscription-3',
  //   href: null,
  //   target: null,
  // },
  {
    id: '731yh',
    title: 'Gallery',
    icon: 'collections',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '7895i',
    title: 'Image Folder',
    icon: null,
    hasSubMenu: false,
    parentId: '731yh',
    routerLink: 'image-folder',
    href: null,
    target: null,
  },
  // Parent Gallery
  {
    id: '7896i3',
    title: 'Image Gallery',
    icon: null,
    hasSubMenu: false,
    parentId: '731yh',
    routerLink: 'image-gallery',
    href: null,
    target: null,
  },
];
export const menuItemsAdmin: MenuAdmin[] = [
  {
    id: '1',
    title: 'Dashboard',
    icon: 'dashboard',
    hasSubMenu: false,
    parentId: null,
    routerLink: 'dashboard',
    href: null,
    target: null,
  },
  {
    id: '6',
    title: 'Product',
    icon: 'list_alt',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },

  {
    id: '6sub2',
    title: 'Add Product',
    icon: null,
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'add-product',
    href: null,
    target: null,
  },
  {
    id: '6sub1',
    title: 'Products List',
    icon: null,
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'products',
    href: null,
    target: null,
  },
];
export const menuItemsEditor: MenuAdmin[] = [
  {
    id: '1',
    title: 'Dashboard',
    icon: 'dashboard',
    hasSubMenu: false,
    parentId: null,
    routerLink: 'dashboard',
    href: null,
    target: null,
  },
  {
    id: '6',
    title: 'Product',
    icon: 'list_alt',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },

  {
    id: '6sub2',
    title: 'Add Product',
    icon: null,
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'add-product',
    href: null,
    target: null,
  },
  {
    id: '6sub1',
    title: 'Products List',
    icon: null,
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'products',
    href: null,
    target: null,
  },
];
export const menuItemsVendor: MenuAdmin[] = [
  {
    id: '1',
    title: 'Dashboard',
    icon: 'dashboard',
    hasSubMenu: false,
    parentId: null,
    routerLink: 'dashboard',
    href: null,
    target: null,
  },
  {
    id: '6',
    title: 'Product',
    icon: 'list_alt',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },

  {
    id: '6sub2',
    title: 'Add Product',
    icon: null,
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'add-product',
    href: null,
    target: null,
  },
  {
    id: '6sub1',
    title: 'Products List',
    icon: null,
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'products',
    href: null,
    target: null,
  },
];
