import { MenuAdmin } from 'src/app/interfaces/menu-admin';

export const menuItemsAdmin: MenuAdmin[] = [
  // Parent Dashboard
  {
    id: '1',
    title: 'Dashboard',
    icon: 'dashboard',
    hasSubMenu: false,
    parentId: null,
    routerLink: 'dashboard',
    href: null,
    target: null,
  },

  // Parent Customization
  {
    id: '2',
    title: 'Customization',
    icon: 'dashboard_customize',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: 'a1',
    title: 'Category Menu',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'category-menu',
    href: null,
    target: null,
  },

  {
    id: 'a2',
    title: 'Carousel',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'carousel',
    href: null,
    target: null,
  },
  {
    id: 'a3',
    title: 'Shop Info',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'shop-info',
    href: null,
    target: null,
  },
  {
    id: 'a4',
    title: 'Footer Data',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'footer-data',
    href: null,
    target: null,
  },
  {
    id: 'a5',
    title: 'Promo Advertise',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'promo-page',
    href: null,
    target: null,
  },
  // Parent Products
  {
    id: '3',
    title: 'Categories',
    icon: 'category',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: 'b1',
    title: 'Attributes',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '3',
    routerLink: 'attributes',
    href: null,
    target: null,
  },
  {
    id: 'b10',
    title: 'Tags',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '3',
    routerLink: 'tags',
    href: null,
    target: null,
  },
  {
    id: 'b2',
    title: 'Brands',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '3',
    routerLink: 'brands',
    href: null,
    target: null,
  },
  {
    id: 'b3',
    title: 'Categories',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '3',
    routerLink: 'category',
    href: null,
    target: null,
  },
  {
    id: 'b3',
    title: 'Sub Categories',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '3',
    routerLink: 'sub-categories',
    href: null,
    target: null,
  },
  // Parent Products
  {
    id: '100',
    title: 'Products',
    icon: 'view_list',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '100b1',
    title: 'Products List',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '100',
    routerLink: 'products',
    href: null,
    target: null,
  },
  {
    id: '100b1',
    title: 'Linked Products List ',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '100',
    routerLink: 'products',
    href: null,
    target: null,
  },
  {
    id: '100b2',
    title: 'Add Product',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '100',
    routerLink: 'add-product',
    href: null,
    target: null,
  },
  {
    id: '100b3',
    title: 'Conversion Rate',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '100',
    routerLink: 'conversion-rate',
    href: null,
    target: null,
  },

  // {
  //   id: 'g',
  //   title: 'Gallery',
  //   icon: 'view_list',
  //   hasSubMenu: true,
  //   parentId: null,
  //   routerLink: '',
  //   href: null,
  //   target: null,
  // },
  // {
  //   id: 'g1',
  //   title: 'Image Folder',
  //   icon: 'folder',
  //   hasSubMenu: false,
  //   parentId: 'g',
  //   routerLink: 'image-folder',
  //   href: null,
  //   target: null,
  // },
  // {
  //   id: 'g2',
  //   title: 'Image Gallery',
  //   icon: 'collections',
  //   hasSubMenu: false,
  //   parentId: 'g',
  //   routerLink: 'image-gallery',
  //   href: null,
  //   target: null,
  // },
  // Parent Offer
  {
    id: '745Z',
    title: 'Offers',
    icon: 'local_offer',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '74RX',
    title: 'Deal on Play',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '745Z',
    routerLink: 'deal-on-play',
    href: null,
    target: null,
  },
  {
    id: '74RY',
    title: 'Deal of The Day',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '745Z',
    routerLink: 'deal-of-the-day',
    href: null,
    target: null,
  },
  {
    id: '74RZ',
    title: 'Featured Product',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '745Z',
    routerLink: 'featured-product',
    href: null,
    target: null,
  },
  {
    id: '74RZ2',
    title: 'Featured Category',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '745Z',
    routerLink: 'featured-category',
    href: null,
    target: null,
  },
  // Parent Coupons
  {
    id: '8',
    title: 'Coupons',
    icon: 'vpn_key',
    hasSubMenu: false,
    parentId: '745Z',
    routerLink: 'coupons',
    href: null,
    target: null,
  },
  {
    id: '74BRY',
    title: 'Banner',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '745Z',
    routerLink: 'banner',
    href: null,
    target: null,
  },
  {
    id: '932r',
    title: 'Promotional Offer',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '745Z',
    routerLink: 'promotional-offer',
    href: null,
    target: null,
  },
  {
    id: '1024',
    title: 'Offer products',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '745Z',
    routerLink: 'offer-products',
    href: null,
    target: null,
  },
  // Parent Gallery Folder
  {
    id: '731',
    title: 'Gallery',
    icon: 'collections',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '45x',
    title: 'Image Folder',
    icon: 'folder',
    hasSubMenu: false,
    parentId: '731',
    routerLink: 'image-folder',
    href: null,
    target: null,
  },
  // Parent Gallery
  {
    id: '4',
    title: 'Image Gallery',
    icon: 'collections',
    hasSubMenu: false,
    parentId: '731',
    routerLink: 'image-gallery',
    href: null,
    target: null,
  },
  {
    id: '7895i',
    title: 'Installations and Repair',
    icon: 'build',
    hasSubMenu: true,
    parentId: null,
    routerLink: 'null',
    href: null,
    target: null,
  },
  {
    id: '7896i',
    title: 'Add New Type',
    icon: 'build',
    hasSubMenu: false,
    parentId: '7895i',
    routerLink: 'installations-and-repair-type',
    href: null,
    target: null,
  },
  {
    id: '7897i',
    title: 'Installations and Repair',
    icon: 'build',
    hasSubMenu: false,
    parentId: '7895i',
    routerLink: 'installations-and-repair',
    href: null,
    target: null,
  },
  // Parent Additional Pages
  {
    id: '45x',
    title: 'Additional Pages',
    icon: 'layers',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '45xd21',
    title: 'About Us Pages',
    icon: 'layers',
    hasSubMenu: false,
    parentId: '45x',
    routerLink: 'about-us-pages',
    href: null,
    target: null,
  },
  {
    id: '45xd22',
    title: 'Other Pages',
    icon: 'layers',
    hasSubMenu: false,
    parentId: '45x',
    routerLink: 'additional-pages',
    href: null,
    target: null,
  },
  {
    id: '45xd232',
    title: 'FAQ',
    icon: 'layers',
    hasSubMenu: false,
    parentId: '45x',
    routerLink: 'faq',
    href: null,
    target: null,
  },

  // Parent Sales
  {
    id: '4',
    title: 'Sales',
    icon: 'local_mall',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: 'c1',
    title: 'Orders',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '4',
    routerLink: 'orders',
    href: null,
    target: null,
  },
  {
    id: 'c1',
    title: 'Transactions',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '4',
    routerLink: 'transactions',
    href: null,
    target: null,
  },
  {
    id: '45x54156',
    title: 'Shipping Charge',
    icon: 'attach_money',
    hasSubMenu: false,
    parentId: '4',
    routerLink: 'shipping-charge',
    href: null,
    target: null,
  },
  {
    id: '4544yz',
    title: 'Best Selling Products',
    icon: 'attach_money',
    hasSubMenu: false,
    parentId: '4',
    routerLink: 'best-sell-products',
    href: null,
    target: null,
  },
  {
    id: '45yz',
    title: 'Warranty Dashboard',
    icon: 'attach_money',
    hasSubMenu: false,
    parentId: '4',
    routerLink: 'warranty-dashboard',
    href: null,
    target: null,
  },
  {
    id: '45y56',
    title: 'Product Authenticators',
    icon: 'attach_money',
    hasSubMenu: false,
    parentId: '4',
    routerLink: 'product-authenticators',
    href: null,
    target: null,
  },
  // Roles Users
  {
    id: '631',
    title: 'Admin Control',
    icon: 'offline_bolt',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '51',
    title: 'Roles',
    icon: 'offline_bolt',
    hasSubMenu: false,
    parentId: '631',
    routerLink: 'roles',
    href: null,
    target: null,
  },
  // Parent Users
  {
    id: '5',
    title: 'Users',
    icon: 'group_add',
    hasSubMenu: false,
    parentId: '631',
    routerLink: 'users',
    href: null,
    target: null,
  },
  // Parent Customers
  {
    id: '6',
    title: 'Customers',
    icon: 'people',
    hasSubMenu: false,
    parentId: null,
    routerLink: 'customers',
    href: null,
    target: null,
  },
  // Parent
  {
    id: '412p',
    title: 'Blog Area',
    icon: 'rss_feed',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '412c',
    title: 'Blogs',
    icon: 'people',
    hasSubMenu: false,
    parentId: '412p',
    routerLink: 'blogs',
    href: null,
    target: null,
  },

  {
    id: '413c',
    title: 'Career at Esquire',
    icon: 'people',
    hasSubMenu: false,
    parentId: '412p',
    routerLink: 'career-esquire',
    href: null,
    target: null,
  },
  // Parent Reviews
  {
    id: 'push123',
    title: 'Push Notification',
    icon: 'notifications',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: 'p10',
    title: 'App List',
    icon: 'list',
    hasSubMenu: false,
    parentId: 'push123',
    routerLink: null,
    href: 'https://app.onesignal.com',
    target: '_blank',
  },
  {
    id: 'p11',
    title: 'Dashboard',
    icon: 'space_dashboard',
    hasSubMenu: false,
    parentId: 'push123',
    routerLink: null,
    href: 'https://app.onesignal.com/apps/133cae47-429e-44a4-bf2a-34a47562793c',
    target: '_blank',
  },
  {
    id: 'p12',
    title: 'Add Notification',
    icon: 'add',
    hasSubMenu: false,
    parentId: 'push123',
    routerLink: null,
    href: 'https://app.onesignal.com/apps/133cae47-429e-44a4-bf2a-34a47562793c/notifications/new',
    target: '_blank',
  },
  // Parent
  {
    id: '7',
    title: 'Contact Us',
    icon: 'drafts',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '7newsletter',
    title: 'Newsletter',
    icon: 'drafts',
    hasSubMenu: false,
    parentId: '7',
    routerLink: 'newsletter',
    href: null,
    target: null,
  },
  {
    id: '7contact',
    title: 'Contact Data',
    icon: 'drafts',
    hasSubMenu: false,
    parentId: '7',
    routerLink: 'contact-us',
    href: null,
    target: null,
  },

  // Parent StoreInfo
  {
    id: '2bc3',
    title: 'Store and Dealer',
    icon: 'offline_bolt',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '777',
    title: 'Store Info',
    icon: 'vpn_key',
    hasSubMenu: false,
    parentId: '2bc3',
    routerLink: 'store-info',
    href: null,
    target: null,
  },
  {
    id: '763',
    title: 'Dealer Info',
    icon: 'vpn_key',
    hasSubMenu: false,
    parentId: '2bc3',
    routerLink: 'dealer-info',
    href: null,
    target: null,
  },
  // Parent Reviews
  {
    id: '8rd2',
    title: 'Review and Discussion',
    icon: 'offline_bolt',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '9',
    title: 'Reviews',
    icon: 'reviews',
    hasSubMenu: false,
    parentId: '8rd2',
    routerLink: 'reviews',
    href: null,
    target: null,
  },
  {
    id: '911',
    title: 'Discussion',
    icon: 'reviews',
    hasSubMenu: false,
    parentId: '8rd2',
    routerLink: 'discussions',
    href: null,
    target: null,
  },

  // Parent Support
  {
    id: '10',
    title: 'Support',
    icon: 'support_agent',
    hasSubMenu: false,
    parentId: null,
    routerLink: null,
    href: 'https://softlabit.com/',
    target: '_blank',
  },
];

export const menuItemsSuperAdmin: MenuAdmin[] = [
  // Parent Dashboard
  // Parent Gallery Folder

  {
    id: '1',
    title: 'Dashboard',
    icon: 'dashboard',
    hasSubMenu: false,
    parentId: null,
    routerLink: 'dashboard',
    href: null,
    target: null,
  },
  {
    id: '6',
    title: 'Product/Category',
    icon: 'view_list',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '6sub1',
    title: 'Products List',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'products',
    href: null,
    target: null,
  },
  {
    id: '100b45',
    title: 'Linked Products List',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'products-by-link',
    href: null,
    target: null,
  },
  {
    id: '6sub2',
    title: 'Add Product',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'add-product',
    href: null,
    target: null,
  },
  {
    id: '110b3',
    title: 'Add By Link',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'add-by-link',
    href: null,
    target: null,
  },
  {
    id: '5',
    title: 'Categories',
    icon: 'category',
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'category',
    href: null,
    target: null,
  },
  {
    id: '100b566',
    title: 'Brand',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'brand',
    href: null,
    target: null,
  },
  {
    id: '100b3',
    title: 'Settings',
    icon: 'follow_the_signs',
    hasSubMenu: true,
    parentId: '6',
    routerLink: 'settings',
    href: null,
    target: null,
  },

  {
    id: '2',
    title: 'Vendors',
    icon: 'dashboard_customize',
    hasSubMenu: false,
    parentId: '100b3',
    routerLink: 'vendor',
    href: null,
    target: null,
  },
  {
    id: '7',
    title: 'Size Chart',
    icon: 'view_list',
    hasSubMenu: false,
    parentId: '100b3',
    routerLink: 'size-chart',
    href: null,
    target: null,
  },
  {
    id: '8',
    title: 'Stock-Control',
    icon: 'view_list',
    hasSubMenu: false,
    parentId: '100b3',
    routerLink: 'stock-control',
    href: null,
    target: null,
  },
  {
    id: '110b3',
    title: 'Conversion Rate',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '6',
    routerLink: 'conversion-rate',
    href: null,
    target: null,
  },

  {
    id: '9',
    title: 'Orders',
    icon: 'view_list',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '3',
    title: 'Customers/Users',
    icon: 'dashboard_customize',
    hasSubMenu: true,
    parentId: null,
    routerLink: 'all-customers',
    href: null,
    target: null,
  },
  {
    id: '3sub1',
    title: 'All Customers',
    icon: 'dashboard_customize',
    hasSubMenu: false,
    parentId: '3',
    routerLink: 'all-customers',
    href: null,
    target: null,
  },
  {
    id: '3sub2',
    title: 'Tag',
    icon: 'dashboard_customize',
    hasSubMenu: false,
    parentId: '3',
    routerLink: 'tag',
    href: null,
    target: null,
  },
  // pareny location
  {
    id: 'l100',
    title: 'Locations',
    icon: 'view_list',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null
  },
  {
    id: '1212ll',
    title: 'Zila',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: 'l100',
    routerLink: 'zila',
    href: null,
    target: null
  },
  {
    id: 'll1121',
    title: 'City',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: 'l100',
    routerLink: 'city',
    href: null,
    target: null
  },

  {
    id: '1212ll',
    title: 'Thana',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: 'l100',
    routerLink: 'thana',
    href: null,
    target: null
  },


  // {
  //   id: '8769',
  //   title: 'Zone',
  //   icon: 'collections',
  //   hasSubMenu: true,
  //   parentId: null,
  //   routerLink: null,
  //   href: null,
  //   target: null,
  // },
  // {
  //   id: '677bbb',
  //   title: 'City',
  //   icon: 'folder',
  //   hasSubMenu: false,
  //   parentId: '8769',
  //   routerLink: 'zone/add-city',
  //   href: null,
  //   target: null,
  // },
  // {
  //   id: '677bbb',
  //   title: 'Zila',
  //   icon: 'folder',
  //   hasSubMenu: false,
  //   parentId: '8769',
  //   routerLink: 'zone/add-zila',
  //   href: null,
  //   target: null,
  // },
  // {
  //   id: '677bbb',
  //   title: 'Thana',
  //   icon: 'folder',
  //   hasSubMenu: false,
  //   parentId: '8769',
  //   routerLink: 'zone/add-thana',
  //   href: null,
  //   target: null,
  // },
  {
    id: '11',
    title: 'Issue',
    icon: 'dashboard_customize',
    hasSubMenu: false,
    parentId: null,
    routerLink: 'dashboard-cusrt',
    href: null,
    target: null,
  },
  {
    id: '12',
    title: '  ',
    icon: 'dashboard_customize',
    hasSubMenu: false,
    parentId: '12',
    routerLink: 'tag',
    href: null,
    target: null,
  },
  {
    id: 'p12',
    title: 'Coupon',
    icon: 'dashboard_customize',
    hasSubMenu: false,
    parentId: '12',
    routerLink: 'tag',
    href: null,
    target: null,
  },
  {
    id: 'p12',
    title: 'Bulk Sms/Email',
    icon: 'dashboard_customize',
    hasSubMenu: false,
    parentId: '12',
    routerLink: 'tag',
    href: null,
    target: null,
  },
  {
    id: 'p12',
    title: 'Campaign',
    icon: 'dashboard_customize',
    hasSubMenu: false,
    parentId: '12',
    routerLink: 'tag',
    href: null,
    target: null,
  },
  {
    id: '13',
    title: 'Settings',
    icon: 'dashboard_customize',
    hasSubMenu: false,
    parentId: null,
    routerLink: 'settings3',
    href: null,
    target: null,
  },
  {
    id: '14',
    title: 'Shipping',
    icon: 'dashboard_customize',
    hasSubMenu: false,
    parentId: null,
    routerLink: 'shipping-4',
    href: null,
    target: null,
  },
  {
    id: '15',
    title: 'Subscription',
    icon: 'dashboard_customize',
    hasSubMenu: false,
    parentId: null,
    routerLink: 'subscription-3',
    href: null,
    target: null,
  },

  // Parent Customization
  {
    id: '2',
    title: 'Customization',
    icon: 'dashboard_customize',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: 'a1',
    title: 'Category Menu',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'category-menu',
    href: null,
    target: null,
  },

  {
    id: 'a2',
    title: 'Carousel',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'carousel',
    href: null,
    target: null,
  },
  {
    id: 'a3',
    title: 'Shop Info',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'shop-info',
    href: null,
    target: null,
  },
  {
    id: 'a4',
    title: 'Footer Data',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'footer-data',
    href: null,
    target: null,
  },
  {
    id: 'a5',
    title: 'Promo Advertise',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'promo-page',
    href: null,
    target: null,
  },

  {
    id: '4',
    title: 'Category Menu',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'category-menu',
    href: null,
    target: null,
  },

  // Parent Products

  {
    id: '9sub1',
    title: 'Regular Order',
    icon: 'view_list',
    hasSubMenu: false,
    parentId: '9',
    routerLink: 'regular-orders',
    href: null,
    target: null,
  },
  {
    id: '9sub2',
    title: 'Request Order',
    icon: 'view_list',
    hasSubMenu: false,
    parentId: '9',
    routerLink: 'request-order',
    href: null,
    target: null,
  },
  {
    id: '9sub3',
    title: 'Return',
    icon: 'view_list',
    hasSubMenu: false,
    parentId: '9',
    routerLink: 'return',
    href: null,
    target: null,
  },
  {
    id: '9sub4',
    title: 'All Invoices',
    icon: 'view_list',
    hasSubMenu: false,
    parentId: '9',
    routerLink: 'all-invoice',
    href: null,
    target: null,
  },
  {
    id: '9sub8',
    title: 'Abandoned Cart',
    icon: 'view_list',
    hasSubMenu: false,
    parentId: '9',
    routerLink: 'abandoned-cart',
    href: null,
    target: null,
  },
  {
    id: '9sub10',
    title: 'Subscription',
    icon: 'view_list',
    hasSubMenu: false,
    parentId: '9',
    routerLink: 'suhna',
    href: null,
    target: null,
  },
  // {
  //   id: '9sub10',
  //   title: 'Subscription',
  //   icon: 'view_list',
  //   hasSubMenu: false,
  //   parentId: '9',
  //   routerLink: 'subscription-3',
  //   href: null,
  //   target: null,
  // },
  {
    id: '731yh',
    title: 'Gallery',
    icon: 'collections',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '7895i',
    title: 'Image Folder',
    icon: 'folder',
    hasSubMenu: false,
    parentId: '731yh',
    routerLink: 'image-folder',
    href: null,
    target: null,
  },
  // Parent Gallery
  {
    id: '7896i3',
    title: 'Image Gallery',
    icon: 'collections',
    hasSubMenu: false,
    parentId: '731yh',
    routerLink: 'image-gallery',
    href: null,
    target: null,
  },
];

export const menuItemsEditor: MenuAdmin[] = [
  // Parent Dashboard
  {
    id: '1',
    title: 'Dashboard',
    icon: 'dashboard',
    hasSubMenu: false,
    parentId: null,
    routerLink: 'dashboard',
    href: null,
    target: null,
  },
  // Parent Customization
  {
    id: '2',
    title: 'Customization',
    icon: 'dashboard_customize',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: 'a1',
    title: 'Category Menu',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'category-menu',
    href: null,
    target: null,
  },

  {
    id: 'a2',
    title: 'Carousel',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'carousel',
    href: null,
    target: null,
  },
  {
    id: 'a3',
    title: 'Shop Info',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'shop-info',
    href: null,
    target: null,
  },
  {
    id: 'a4',
    title: 'Footer Data',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '2',
    routerLink: 'footer-data',
    href: null,
    target: null,
  },
  // Parent Products
  {
    id: '3',
    title: 'Categories',
    icon: 'category',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: 'b1',
    title: 'Attributes',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '3',
    routerLink: 'attributes',
    href: null,
    target: null,
  },
  {
    id: 'b10',
    title: 'Tags',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '3',
    routerLink: 'tags',
    href: null,
    target: null,
  },
  {
    id: 'b2',
    title: 'Brands',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '3',
    routerLink: 'brands',
    href: null,
    target: null,
  },
  {
    id: 'b3',
    title: 'Categories',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '3',
    routerLink: 'category',
    href: null,
    target: null,
  },
  {
    id: 'b3',
    title: 'Sub Categories',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '3',
    routerLink: 'sub-categories',
    href: null,
    target: null,
  },
  // Parent Products
  {
    id: '100',
    title: 'Products',
    icon: 'view_list',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '100b1',
    title: 'Products List',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '100',
    routerLink: 'products',
    href: null,
    target: null,
  },
  {
    id: '100b1',
    title: 'Linked Products List ',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '100',
    routerLink: 'products',
    href: null,
    target: null,
  },
  {
    id: '100b2',
    title: 'Add Product',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '100',
    routerLink: 'add-product',
    href: null,
    target: null,
  },

  // Parent Offer
  {
    id: '100b3',
    title: 'Conversion Rate',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '100',
    routerLink: 'conversion-rate',
    href: null,
    target: null,
  },

  {
    id: '745Z',
    title: 'Offers',
    icon: 'local_offer',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '74RX',
    title: 'Deal on Play',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '745Z',
    routerLink: 'deal-on-play',
    href: null,
    target: null,
  },
  {
    id: '74RY',
    title: 'Deal of The Day',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '745Z',
    routerLink: 'deal-of-the-day',
    href: null,
    target: null,
  },
  {
    id: '74RZ',
    title: 'Featured Product',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '745Z',
    routerLink: 'featured-product',
    href: null,
    target: null,
  },
  {
    id: '74RZ2',
    title: 'Featured Category',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '745Z',
    routerLink: 'featured-category',
    href: null,
    target: null,
  },
  // Parent Coupons
  {
    id: '8',
    title: 'Coupons',
    icon: 'vpn_key',
    hasSubMenu: false,
    parentId: '745Z',
    routerLink: 'coupons',
    href: null,
    target: null,
  },
  {
    id: '74BRY',
    title: 'Banner',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '745Z',
    routerLink: 'banner',
    href: null,
    target: null,
  },
  {
    id: '932r',
    title: 'Promotional Offer',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '745Z',
    routerLink: 'promotional-offer',
    href: null,
    target: null,
  },
  {
    id: '1024',
    title: 'Offer products',
    icon: 'follow_the_signs',
    hasSubMenu: false,
    parentId: '745Z',
    routerLink: 'offer-products',
    href: null,
    target: null,
  },
  // Parent Gallery Folder
  {
    id: '731yh',
    title: 'Gallery',
    icon: 'collections',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '7895i',
    title: 'Image Folder',
    icon: 'folder',
    hasSubMenu: false,
    parentId: '731yh',
    routerLink: 'image-folder',
    href: null,
    target: null,
  },
  // Parent Gallery
  {
    id: '7896i3',
    title: 'Image Gallery',
    icon: 'collections',
    hasSubMenu: false,
    parentId: '731yh',
    routerLink: 'image-gallery',
    href: null,
    target: null,
  },
  {
    id: '7895i',
    title: 'Installations and Repair',
    icon: 'build',
    hasSubMenu: true,
    parentId: null,
    routerLink: 'null',
    href: null,
    target: null,
  },
  {
    id: '7896i',
    title: 'Add New Type',
    icon: 'build',
    hasSubMenu: false,
    parentId: '7895i',
    routerLink: 'installations-and-repair-type',
    href: null,
    target: null,
  },
  {
    id: '7897i',
    title: 'Installations and Repair',
    icon: 'build',
    hasSubMenu: false,
    parentId: '7895i',
    routerLink: 'installations-and-repair',
    href: null,
    target: null,
  },
  // Parent Additional Pages
  {
    id: '45x',
    title: 'Additional Pages',
    icon: 'layers',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '45xd21',
    title: 'About Us Pages',
    icon: 'layers',
    hasSubMenu: false,
    parentId: '45x',
    routerLink: 'about-us-pages',
    href: null,
    target: null,
  },
  {
    id: '45xd22',
    title: 'Other Pages',
    icon: 'layers',
    hasSubMenu: false,
    parentId: '45x',
    routerLink: 'additional-pages',
    href: null,
    target: null,
  },
  {
    id: '45xd232',
    title: 'FAQ',
    icon: 'layers',
    hasSubMenu: false,
    parentId: '45x',
    routerLink: 'faq',
    href: null,
    target: null,
  },
  // Parent
  {
    id: '412p',
    title: 'Blog Area',
    icon: 'rss_feed',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '412c',
    title: 'Blogs',
    icon: 'people',
    hasSubMenu: false,
    parentId: '412p',
    routerLink: 'blogs',
    href: null,
    target: null,
  },

  {
    id: '413c',
    title: 'Career at Esquire',
    icon: 'people',
    hasSubMenu: false,
    parentId: '412p',
    routerLink: 'career-esquire',
    href: null,
    target: null,
  },
  // Parent
  {
    id: '7',
    title: 'Contact Us',
    icon: 'drafts',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '7newsletter',
    title: 'Newsletter',
    icon: 'drafts',
    hasSubMenu: false,
    parentId: '7',
    routerLink: 'newsletter',
    href: null,
    target: null,
  },
  {
    id: '7contact',
    title: 'Contact Data',
    icon: 'drafts',
    hasSubMenu: false,
    parentId: '7',
    routerLink: 'contact-us',
    href: null,
    target: null,
  },

  // Parent StoreInfo
  {
    id: '2bc3',
    title: 'Store and Dealer',
    icon: 'offline_bolt',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '777',
    title: 'Store Info',
    icon: 'vpn_key',
    hasSubMenu: false,
    parentId: '2bc3',
    routerLink: 'store-info',
    href: null,
    target: null,
  },
  {
    id: '763',
    title: 'Dealer Info',
    icon: 'vpn_key',
    hasSubMenu: false,
    parentId: '2bc3',
    routerLink: 'dealer-info',
    href: null,
    target: null,
  },
  // Parent Reviews
  {
    id: '8rd2',
    title: 'Review and Discussion',
    icon: 'offline_bolt',
    hasSubMenu: true,
    parentId: null,
    routerLink: null,
    href: null,
    target: null,
  },
  {
    id: '9',
    title: 'Reviews',
    icon: 'reviews',
    hasSubMenu: false,
    parentId: '8rd2',
    routerLink: 'reviews',
    href: null,
    target: null,
  },
  {
    id: '911',
    title: 'Discussion',
    icon: 'reviews',
    hasSubMenu: false,
    parentId: '8rd2',
    routerLink: 'discussion',
    href: null,
    target: null,
  },
  // Parent Support
  {
    id: '10',
    title: 'Support',
    icon: 'support_agent',
    hasSubMenu: false,
    parentId: null,
    routerLink: null,
    href: 'https://softlabit.com/',
    target: '_blank',
  },

// parent zoon


];
